version: '3.8'

services:
  mongo:
    image: mongo
    container_name: otus-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - 27023:27017